services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      DOMAIN: https://${MAIN_DOMAIN}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: "true"
    volumes:
      - vw-data:/data

volumes:
  vw-data:
