services:
  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    expose:
      - "8025"
    ports:
      - "${SMTP_PORT}:1025"
    volumes:
      - mailpit-data:/data
    environment:
      MP_DATABASE: /data/mailpit.db

volumes:
  mailpit-data:
